### ISSUE TITLE
PR463 / SiPixel / Marco Musich / relval: PCL renderplugin update

### ISSUE THREAD

**Issue by threus** [cms-DQM/PR-workflow-tracking-for-DQM-GUI#57]
https://github.com/dmwm/deployment/pull/463

**Comment by vanbesien** [comment]
This is actually relval. But it doesn't matter really. And on top of that there is no way to know, because render plugins are shared amongst all flavors. I just remember it because Marco was skyping me about his development.

**Comment by mmusich** [comment]
Hi @vanbesien @threus, thanks for following up the request. 
Sorry I didn't specify the flavor of the GUI in the first place.
I think we need it both in relval and offline, if I am not mistaken, since we want to look at this while Express is processed, I don't know if this makes any difference for you. 
Thanks,
Marco

**Comment by vanbesien** [comment]
Not at all :-).
